Fsb 1443 playlistfix
treeti-official/react-native-jw-media-player pull request #7
Opened 2020-03-02 10:16 UTC by JanSunavec

2020-03-02 13:15 UTC, davidblanar requested changes

2020-03-02 13:15 UTC, davidblanar commented on ios/RNJWPlayerNativeView.m
> +//    NSLog(@"MEGA MEFA %@", nextUpOffset);
remove

2020-03-02 13:57 UTC, n1o approved these changes

2020-03-04 10:32 UTC, davidblanar approved these changes

2020-03-04 10:33 UTC, merged