Fsb 1466
treeti-official/react-native-jw-media-player pull request #8
Opened 2020-03-05 10:26 UTC by davidblanar

https://nuuvuu.atlassian.net/browse/FSB-1466

2020-03-05 11:33 UTC, n1o requested changes

2020-03-05 11:33 UTC, n1o commented on android/src/main/java/com/appgoalz/rnjwplayer/RNJWPlayerView.java
> +            isFullscreen = true;
tu nie je ziaden dovod assumovat ze to je synchrony kod. Toto musi byt but atomic alebo sychronized

2020-03-06 14:14 UTC, JanSunavec approved these changes
Mega epicke riesenie pre multithread border.

2020-03-09 13:15 UTC, n1o approved these changes

2020-03-09 13:16 UTC, merged